### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by Pascal666** [mythic-beasts/pvshrink#2]
pvshrink yields the below error when run under Python 3.8:
Traceback (most recent call last):
  File "./pvshrink", line 118, in <module>
    match = re.search(r'Found text metadata area: offset=(\d+), size=(\d+)', pvck)
  File "/usr/lib64/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by ekuester** [comment]
This error  is the same as in issue #1 and can be solved similarly. For further information look for instance under [StackOverflow](https://stackoverflow.com/questions/31019854/typeerror-cant-use-a-string-pattern-on-a-bytes-like-object-in-re-findall) or [this tutorial](https://www.tutorialexample.com/fix-typeerror-cannot-use-a-string-pattern-on-a-bytes-like-object-python-tutorial/)

Fortunately the error occurred after defragmentation, so in my case I could solve the resizing manually and do not want to repeat the operation on my harddisk (for further testing of code).
